### ISSUE TITLE
How does $options work?

### ISSUE THREAD

**Issue by ammonkc** [codezero-be/mailer#1]
It's unclear in the documentation how to set additional $options on the message. How would I set $message->from()?

**Comment by ivanvermeyen** [comment]
Hi

At this point the `$options` parameter can be a function that accepts the `$message` object from Laravel.
Details about this object can be found on http://laravel.com/docs/5.1/mail#sending-mail.

So for example:

```
$options = function ($message) {
    $message->from('us@example.com', 'Laravel');
    $message->to('foo@example.com')
                    ->cc('bar@example.com');
}
```

**Comment by ammonkc** [comment]
Hi Thanks! Thats exactly what I needed. This is a really nice mailer package you've put together.

**Comment by ivanvermeyen** [comment]
Thanks! Glad you like it :)
